import { type NextPage } from "next";
import Head from "next/head";
import { useUser, SignInButton, SignOutButton } from "@clerk/nextjs";
import { api } from "~/utils/api";
import PostView from "~/Components/PostView";
import CreatePostWizard from "~/Components/CreatePostWizard";

const Home: NextPage = () => {
  const { data, isLoading } = api.posts.getAll.useQuery();
  const user = useUser();

  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Something went wrong on out end... Sorry champ.</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-screen border-x border-slate-400 md:max-w-2xl">
          <h1 className="justify-self-end text-white">Emitter App!</h1>
          {!!user.isSignedIn && (
            <SignOutButton>
              <button className="btn border-zinc-300 text-white">
                Sign Out
              </button>
            </SignOutButton>
          )}
          <div className="flex w-full border-b p-4">
            {!!user.isSignedIn && <CreatePostWizard />}
            {!user.isSignedIn && (
              <>
                <SignInButton mode="modal">
                  <button className="btn border-zinc-300 text-white">
                    Sign In
                  </button>
                </SignInButton>
              </>
            )}
          </div>

          {data?.map((fullPost) => {
            return <PostView {...fullPost} key={fullPost.post.id} />;
          })}
        </div>
      </main>
    </>
  );
};

export default Home;
