import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import {
  useUser,
  SignInButton,
  SignUpButton,
  SignOutButton,
} from "@clerk/nextjs";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="text-white">Emitter App!</h1>
        {!!user.isSignedIn && (
          <p className="text-white">Welcome {user.user.username}</p>
        )}
        {!user.isSignedIn && (
          <>
            <SignUpButton mode="modal">
              <button className="btn border-zinc-300 text-white">
                Register
              </button>
            </SignUpButton>
            <SignInButton mode="modal">
              <button className="btn border-zinc-300 text-white">
                Sign In
              </button>
            </SignInButton>
          </>
        )}
        {!!user.isSignedIn && (
          <SignOutButton>
            <button className="btn border-zinc-300 text-white">Sign Out</button>
          </SignOutButton>
        )}
      </main>
    </>
  );
};

export default Home;
