import { type NextPage } from "next";
import Head from "next/head";
import { useUser, SignInButton, SignOutButton } from "@clerk/nextjs";
import { RouterOutputs, api } from "~/utils/api";

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;
  console.log(user);

  return (
    <div className="flex w-full gap-3">
      <img
        src={user.profileImageUrl}
        alt={`Image of the user, ${user.username}`}
        className="h-16 w-16 rounded-full"
      />
      <input
        type="text"
        placeholder="Type some emojis..."
        className="w-11/12 grow bg-transparent p-4"
      />
    </div>
  );
};

type postWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: postWithUser) => {
  const { post, author } = props;

  return (
    <div key={post?.id} className="border-clate-400 flex gap-6 border-b p-8">
      <img
        src={author?.profileImageUrl}
        alt={`${author?.username} profile image`}
        className="h-12 w-12 justify-self-start rounded-full"
      />
      <p className="text-white">{post?.content}</p>
    </div>
  );
};

const Home: NextPage = () => {
  const { data, isLoading } = api.posts.getAll.useQuery();
  const user = useUser();

  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Something went wrong on out end... Sorry champ.</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-screen border-x border-slate-400 md:max-w-2xl">
          <h1 className="justify-self-end text-white">Emitter App!</h1>
          {!!user.isSignedIn && (
            <SignOutButton>
              <button className="btn border-zinc-300 text-white">
                Sign Out
              </button>
            </SignOutButton>
          )}
          <div className="flex w-full border-b p-4">
            {!!user.isSignedIn && <CreatePostWizard />}
            {!user.isSignedIn && (
              <>
                <SignInButton mode="modal">
                  <button className="btn border-zinc-300 text-white">
                    Sign In
                  </button>
                </SignInButton>
              </>
            )}
          </div>

          {data?.map((fullPost) => {
            return <PostView {...fullPost} key={fullPost.post.id} />;
          })}
        </div>
      </main>
    </>
  );
};

export default Home;
