import Head from "next/head";
import Link from "next/link";
import { useUser, SignOutButton } from "@clerk/nextjs";

const Welcome = () => {
  const user = useUser();

  return (
    <>
      <Head>
        <title>Emitter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="text-white">Welcome {user.user?.username}</h1>
        <SignOutButton>
          <button className="btn border-zinc-300 text-white">Sign Out</button>
        </SignOutButton>
      </main>
    </>
  );
};

export default Welcome;
